### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by Amrutha1101** [antoprince001/QA_Master#1]
Hey, I'm a beginner. Can you please let me know how to run this in local system?

**Comment by antoprince001** [comment]
You can follow the steps below to run locally :

1. Ensure you have python 3.x version installed
2. Clone the project locally and open to the file path in terminal
3. Run ``` pip install -r requirements.txt  ```
4. Then, run  ```python app.py ```
5. If app runs successfully, you can see the application at http://localhost:5000/qafinder
